### ISSUE TITLE
mac compile run failed

### ISSUE THREAD

**Issue by james133** [boilerplate-fe/umi-electron-boilerplate#1]
umi-electron-boilerplate-master % yarn start
yarn run v1.15.2
warning package.json: No license field
$ node scripts/start.js
/Users/yanhua/Downloads/umi-electron-boilerplate-master/scripts/lib/main_hmr.js
[2020-05-27T09:46:13.637] [INFO] main - app ready

umi server start

gui not start

**Comment by DiamondYuan** [comment]
try this version
